language: ruby
rvm:
  - 1.9.3
  #- 2.0.0
  #- 2.1.0
git:
  submodules: false
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - secure: "UOfu9FrGiIMwJV/u2a3cwd4XrDd+KOvpTfJlC+QDLeL3l8ozjD7OUZ4xnA8hFNwzoHUK14hPM+TX7MeT4gN9GdFJqjn9MEhgNnz0pEx9mCVEQyfqnxYiWzU8G3NaMfF1CXiMuU3o04qY1/CkGJD9xpgWs1ksJDoBr8TB63ZWi34="
before_install:
  - openssl aes-256-cbc -K $encrypted_e48ba2f2c6f2_key -iv $encrypted_e48ba2f2c6f2_iv -in .octogray_test_id_rsa.enc -out .octogray_test_id_rsa -d
  - mkdir -p ~/.ssh
  - cp .octogray_test_id_rsa ~/.ssh/id_rsa
  - chmdo 600 ~/.ssh/id_rsa
  #- |
  #  if sed --version 2>/dev/null |grep -q GNU;then
  #    function sedi () {
  #      sed -i"" $*
  #    }
  #  else
  #    function sedi () {
  #      sed -i "" $*
  #    }
  #  fi
  - sed -i"" 's/git@github.com:/https:\/\/github.com\//' .gitmodules
install:
  - cd ~/
  - git clone git://github.com/imathis/octopress.git ./octopress.orig
  - cp -r octopress.orig octopress.master
  - cd ~/octopress.master
  - git submodule add git://github.com/rcmdnk/octogray.git .themes/octogray
  - sed -i"" 's/git@github.com:/https:\/\/github.com\//' .themes/octogray/.gitmodules
  - cd ~/
  - cp -r octopress.orig octopress.gh-pages
  - cd ~/octopress.gh-pages
  - git submodule add git://github.com/rcmdnk/octogray.git .themes/octogray
  - sed -i"" 's/git@github.com:/https:\/\/github.com\//' .themes/octogray/.gitmodules
script:
  - cd ~/octopress.master
  - ./.themes/octogray/setup.sh -y
  - rake setup_github_pages["git@github.com:rcmdnk/test.github.io","yes"]
  - cd ~/octopress.gh-pages
  - ./.themes/octogray/setup.sh -y
  - rake setup_github_pages["https://${GH_TOKEN}@github.com/rcmdnk/octogray_test","yes"]
  - 'post=$(rake new_post["test"]|grep "Creating new post"|cut -d: -f2)'
  - 'sed -i"" "s/published: *false/published: true/" $post'
  - 'sed -i"" "s/categories:/categories: cat/" $post'
  - 'sed -i"" "s/tags:/tags: tag/" $post'
  - sed -i"" "s/<\!-- *more *-->/This is test post."\\$'\n'"<\!-- more -->/" $post
  - sed -i"" "s/{%include after_excerpt.html%}/{%include after_excerpt.html%}"\\$'\n'"# Test Sectiontest"\\$'\n'"test $(date) test./" $post
  - cat $post
  - rake gen
  - rake deploy
  - rake setup_github_pages["git@github.com/rcmdnk/octogray_test","yes"]
  - rake deploy

