language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  #- 2.1.0
git:
  submodules: false
before_install:
  - |
    if sed --version 2>/dev/null |grep -q GNU;then
      function sedi () {
        sed -i"" $*
      }
    else
      function sedi () {
        sed -i "" $*
      }
    fi
  - sedi 's/git@github.com:/https:\/\/github.com\//' .gitmodules
install:
  - cd ~/
  - git clone git://github.com/imathis/octopress.git ./octopress.orig
  - cp -r octopress.orig octopress.master
  - cd ~/octopress.master
  - git submodule add git://github.com/rcmdnk/octogray.git .themes/octogray
  - sedi 's/git@github.com:/https:\/\/github.com\//' .themes/octogray/.gitmodules
  - cd ~/
  - cp -r octopress.orig octopress.gh-pages
  - cd ~/octopress.gh-pages
  - git submodule add git://github.com/rcmdnk/octogray.git .themes/octogray
  - sedi 's/git@github.com:/https:\/\/github.com\//' .themes/octogray/.gitmodules
script:
  - cd ~/octopress.master
  - ./.themes/octogray/setup.sh -y
  - rake setup_github_pages["git@github.com:rcmdnk/test.github.io","yes"]
  - cd ~/octopress.gh-pages
  - ./.themes/octogray/setup.sh -y
  - rake setup_github_pages["git@github.com:rcmdnk/test","yes"]
  - post=$(rake new_post["test"]|grep "Creating new post"|cut -d: -f2)
  - sedi 's/published: *false/published: true/' $post
  - sedi 's/categories:/categories: cat/' $post
  - sedi 's/tags:/tags: tag/' $post
  - sedi "s/<\!-- *more *-->/This is test post."\\$'\n'"<\!-- more -->/" $post
  - sedi "s/{%include after_excerpt.html%}/{%include after_excerpt.html%}"\\$'\n'"# Test Sectiontest"\\$'\n'"test test./" $post
  - rake gen
    #- rake deploy
