language: ruby
branches:
  except:
    - /^v[0-9]/
rvm:
  - 2.4.3
  - 2.5.0
  #- ruby-head
git:
  submodules: false
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
before_install:
  - openssl aes-256-cbc -K $encrypted_4c26257df17f_key -iv $encrypted_4c26257df17f_iv -in .octogray_rsa.enc -out .octogray_rsa -d
  - mkdir -p ~/.ssh
  - cp .octogray_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  #- |
  #  if sed --version 2>/dev/null |grep -q GNU;then
  #    function sedi () {
  #      sed -i"" $*
  #    }
  #  else
  #    function sedi () {
  #      sed -i "" $*
  #    }
  #  fi
  - sed -i"" 's/git@github.com:/https:\/\/github.com\//' .gitmodules
install:
  - cd ~/
  - git clone git://github.com/imathis/octopress.git ./octopress.orig
  - cp -r octopress.orig octopress.master
  - cd ~/octopress.master
  - git submodule add git://github.com/rcmdnk/octogray.git .themes/octogray
  - sed -i"" 's/git@github.com:/https:\/\/github.com\//' .themes/octogray/.gitmodules
  - cd ~/
  - cp -r octopress.orig octopress.gh-pages
  - cd ~/octopress.gh-pages
  - git submodule add git://github.com/rcmdnk/octogray.git .themes/octogray
  - sed -i"" 's/git@github.com:/https:\/\/github.com\//' .themes/octogray/.gitmodules
script:
  - cd ~/octopress.master
  - ./.themes/octogray/setup.sh -y
  - rake setup_github_pages["git@github.com:rcmdnk/test.github.io","yes"]
  - 'post=$(rake new_post["test"]|grep "Creating new post"|cut -d: -f2)'
  - 'sed -i"" "s/published: *false/published: true/" $post'
  - 'sed -i"" "s/categories:/categories: cat/" $post'
  - 'sed -i"" "s/tags:/tags: tag/" $post'
  - sed -i"" "s/<\!-- *more *-->/This is test post."\\$'\n'"<\!-- more -->/" $post
  - sed -i"" "s/{%include after_excerpt.html%}/{%include after_excerpt.html%}"\\$'\n'"# Test Sectiontest"\\$'\n'"test $(date) test./" $post
  - echo >> $post
  - echo "[Code test](/others/codetest/) ">> $post
  - rake generate --trace
  - cd ~/octopress.gh-pages
  - ./.themes/octogray/setup.sh -y -l
  - rake setup_github_pages["git@github.com:rcmdnk/octogray_test","yes"]
  - 'post=$(rake new_post["test"]|grep "Creating new post"|cut -d: -f2)'
  - 'sed -i"" "s/published: *false/published: true/" $post'
  - 'sed -i"" "s/categories:/categories: cat/" $post'
  - 'sed -i"" "s/tags:/tags: tag/" $post'
  - sed -i"" "s/<\!-- *more *-->/This is test post."\\$'\n'"<\!-- more -->/" $post
  - sed -i"" "s/{%include after_excerpt.html%}/{%include after_excerpt.html%}"\\$'\n'"# Test Sectiontest"\\$'\n'"test $(date) test./" $post
  - echo >> $post
  - echo "[Code test](/others/codetest/) ">> $post
  - rake gen --trace
  - rake deploy

