# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: My Octopress Blog
subtitle: A blogging framework for hackers.
author: Your Name
lang: en
favicon: #/images/icon16.png
title_logo:
title_logo_css: false
# Please add your images to there
aboutme_logo: #/images/icon32.png
#aboutme_logo: https://github.com/rcmdnk.png
aboutme_logo_css: false
sitelogo:
description:
imgpath: /images

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"
#date_format: "%d %b %Y"

# time zone
# timezone: UTC

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:
email_mark: false
rss_mark: false

# Navigation
nav_marks: true
nav_links:
  /blog/archives/ : Archives
  /share-checker.html/ : Share Checker
  /windows/ : Windows
  /mac/ : Mac
  /en/ : English Blog

# sidebar
aboutme_marks: false

# jQuery
jquery_version: 2.1.4
jquery_ie8_version: 1.9.1

# Font Awesome
fontawesome_version: 4.5.0

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
tag_dir: blog/tags

markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_number: table
    coderay_css: class

highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "blog/page/:num/"  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on <i class=\"fa fa-hand-o-right\"></i>"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: false       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides:
  #- custom/asides/ad_aside_top.html
  - custom/asides/google_aside_top.html
  - custom/asides/about.html
  - custom/asides/amazon_wishlist.html
  - asides/recent_posts.html
  - custom/asides/monthly_archive.html
  - custom/asides/category_list.html
  - custom/asides/tag_cloud.html
  - custom/asides/popular_posts.html
  - custom/asides/random_posts.html

mytools_asides:
  - custom/asides/twitter_search.html

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# Width of the aside
#aside_width: 300 # set sass/custom/_layout.scss: $sidebar-width-medium as 330px
aside_width: 336 # set sass/custom/_layout.scss: $sidebar-width-medium as 360px

# Related post
related_posts: 20
related_categories: true
related_posts_show: 5
related_posts_text: "You might also like..."

# Aside Pages
aside_pages:
#  /windows/: Windows
#  /mac/: Mac

# 404 not found picture
pic_404nf: #/images/icon200.png

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Set n-cores for Parallel job
n_cores: 8

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Linkchecker
linkchecker: false
linkchecker_travis_user:
linkchecker_travis_repo:

# My tools conents
mytools:

# Share
share_official: false
share_custom: true
share_static: true
share_check_all: true

share_big:
  hatebu: "HatenaBookMark"
  twitter: "Share on Twitter"
  googleplus: "Share on Google+"
  facebook: "Share on Facebook"
  pocket: "Save to Pocket"
  linkedin: "Share on LinkedIn"
  stumble: "Share on StumbleUpon"
  pinterest: "Save to Pinterest"
  buffer: "Share on Buffer"
  delicious: "Save to Delicious"
  tumbr: "Share on Tumblr"
  feedly: "Follow on Feedly"

# Github repositories
github_user:
github_repo_count: 10
github_show_profile_link: true
github_skip_forks: true
github_mark: false

# Twitter
twitter_user:
twitter_follow_button: true
twitter_tweet_button: true
twitter_button: true
twitter_tweet_lang: en
twitter_mark: false
twitter_search:
twitter_only_page: true

# Google +1
googleplus_button: true
google_plus_one_size: medium
google_plus_one_lang: en
google_plus_one_user:
google_plus_one_mark: false

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# LinkedIn
linkedin_user:
linkedin_mark: false
linkedin_button: false
linkedin_lang: ja_JP

# Pinterest
pinterest_button: false

# StumbleUpon
stumble_button: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3
delicious_button: false

# Buffer
buffer_button: false

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false
facebook_share: true
facebook_button: true
facebook_lang: en_US
facebook_app_id:
facebook_user:
facebook_mark: false
facebook_admins_id:

# Favorite, add bookmark button
bookmark: true
bookmark_mark: true
favorite: Favorite

# Hatena Bookmark
hatebu_button: true
hatena_user:
hatena_add: "Add to Hatena Bookmark"
hatena_popular_posts: static # light, feed, orig or static
hatena_popular_sort: count # eid, hot, count
hatena_popular_title: Hatebu Popular Posts
hatena_popular_num: 5

# Pocket
pocket_button: true

# Zenback
zenback_show: false
zenback_widget:

# LinkWithin
linkwithin_show: false
linkwithin_id:
linkwithin_text: "You might also like..."

# pubsubhubbub
hub_url:

# Coderwall badges
coderwall_user:

# feedly
feedly_mark: false
feedly_atom: http://yoursite/atom.xml
feedly_button: false # for the bottom button

# Tumblr
tumblr_button: false

# affiliate
affiliate: false
affiliate_link_unit: false
affiliate_services: "Google Adsense"

# Google Adsense
sponsored_links: "Sponsored Links"
adsense_id:
adsense_aside_top:
adsense_aside_bottom:
adsense_mid:
adsense_bottom:
adsense_link_nav:
adsense_link_bottom:
adsense_link_0:

# Google Translate
google_translate_lang: en
# SIMPLE/TOP_LEFT/TOP_RIGHT/BOTTOM_LEFT/BOTTOM_RIGHT
#google_translate_layout: SIMPLE
#google_translate_customize:

# Search
simple_search: https://www.google.com/search
google_search: false
google_custom_search: twopages
google_result_page: /search.html
google_search_query: s
google_search_pub:
google_search_lang: en

# Amazon tag
#amazon_ad_tag: xxxxxx0c-22
amazon_wishlist: false
amazon_region: US # US or JP
amazon_wish_id:
amazon_wish_words: Wish list
amazon_wish_tag:

# UserLocal
userlocal:

# page-view settings (need service account private key file (key_file). ref: https://github.com/developmentseed/jekyll-ga)
page-view:
  service_account_email:
  key_file: # service account private key file (Analytics-XXXXXXXXXXXX.p12)
  key_secret: notasecret    # service account private key's password
  profileID:  #ga:XXXXXXXX
  start:                    # Beginning of report
    - 1 month ago
    - 10 years ago
    - 1 year ago
    - 1 week ago
    - 1 day ago
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment: gaid::-1         # all visits
  filters:                  # optional
  n_posts: 5                # Number of popular posts
  show_views: false         # If n_views is shown or not
popular_post_title: Most Viewed Posts (Last Month) # Title of sidebar section

# Random posts
random_posts: 5
random_local: false
#random_url: '/posts_light.html'

# Copy check
mandrill: true
mandrill_key:
mandrill_from:
mandrill_to_email:
mandrill_to_name:

# Thumbnails
thumbnails:
  - square-thumbnail
  - small-thumbnail
square-thumbnail-width: 200
square-thumbnail-height: 200
small-thumbnail-width: 120
small-thumbnail-height: 90

# Monthly Archive
monthly_archive_count: true
monthly_archive_open: first
monthly_archive_format: JAN
monthly_format: January

# scroll-fixed
n_scroll_fixed: 0

# scrolltop
scrolltop: false

# Postscript
ps_title: Edit
ps_close:

# gemoji
emoji_dir: /images/emoji

# jekyll-var
jekyll_var:
  include:
    - n_scroll_fixed
    - hatebu_button
    - twitter_button
    - googleplus_button
    - facebook_button
    - pocket_button
    - linkedin_button
    - stumble_button
    - pinterest_button
    - buffer_button
    - delicious_button
    - tumblr_button
    - feedly_button
    - share_static
    - share_no_ga
    - share_check_all
    - mandrill
    - mandrill_key
    - mandrill_from
    - mandrill_to_email
    - mandrill_to_name
    - random_posts
    - random_local
    - random_url
    - related_posts_show
  exclude:
