source "https://rubygems.org"

group :development do
  gem 'chronic', '~> 0.10.2'
  gem 'compass', '~> 1.0.3'
  gem 'csv', '~> 3.3.0'
  gem 'gemoji', '~> 4.1.0'
  gem 'google-analytics-data', '~> 0.6.1'
  gem 'htmlcompressor', '~> 0.4.0'
  gem 'jekyll', '~> 4.3.3'
  gem 'jekyll-paginate', '~> 1.1.0'
  gem 'jekyll-sitemap', '~> 1.4.0'
  gem 'json', '~> 2.8.0'
  gem 'ostruct', '~> 0.6.1'
  gem 'parallel', '~> 1.26.3'
  gem 'pygments.rb', '~> 3.0.0'
  gem 'rackup', '~> 2.2.0'
  gem 'rake', '~>13.2.1'
  gem 'ruby-progressbar', '~> 1.13.0'
  gem 'sass-globbing', '~> 1.1.5'
  gem 'sinatra', '~> 4.1.0'
  gem 'stringex', '~> 2.8.6'
  gem 'xmlrpc', '~> 0.3.3'
  gem 'yui-compressor', '~> 0.12.0'
end
